# Generated by Django 2.2.1 on 2019-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
