# Generated by Django 2.0.8 on 2019-12-19 20:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='entries.Comment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
