# Generated by Django 2.0.8 on 2019-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20191220_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='image',
        ),
        migrations.AddField(
            model_name='entry',
            name='restrict_comment',
            field=models.BooleanField(default=False),
        ),
    ]
